"""Synthetic inputs shared by the scanner tests.

Nothing here touches a real lecture. Audio is generated with numpy, video is
generated by piping raw frames into ffmpeg (and every test that needs one is
skipped when ffmpeg is absent), and metric dictionaries are built from the
rubric table itself so they stay complete when a metric is added.
"""

import os
import shutil
import subprocess
import sys

import numpy as np

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from src.scan import rubric  # noqa: E402

SR = 16000


def have_ffmpeg():
    return shutil.which("ffmpeg") is not None and shutil.which("ffprobe") is not None


# --------------------------------------------------------------------------
# Audio
# --------------------------------------------------------------------------

def tone(freq_hz, seconds, amp=0.5, sr=SR):
    """A pure sine of known frequency and amplitude."""
    t = np.arange(int(round(seconds * sr))) / float(sr)
    return (amp * np.sin(2.0 * np.pi * freq_hz * t)).astype(np.float32)


def quiet_noise(seconds, amp=1e-3, seed=0, sr=SR):
    """Room tone: low-level gaussian noise, well above digital silence."""
    rng = np.random.default_rng(seed)
    return (rng.standard_normal(int(round(seconds * sr))) * amp).astype(np.float32)


def bursty_speech(freqs, cycles=8, quiet_s=1.0, loud_s=4.0, amp=0.5):
    """Tone bursts separated by room tone.

    audio_metrics' VAD takes the 10th percentile of frame energy as the floor
    and calls anything 8 dB above it speech, so a signal has to have both a
    quiet part and a loud part before any speech-conditioned metric exists at
    all. Cycling `freqs` across the bursts is how a monotone signal and a
    pitch-varying one are built from the same helper.
    """
    parts = []
    for i in range(cycles):
        parts.append(quiet_noise(quiet_s, seed=i))
        parts.append(tone(freqs[i % len(freqs)], loud_s, amp=amp))
    return np.concatenate(parts)


# --------------------------------------------------------------------------
# Video
# --------------------------------------------------------------------------

VIDEO_W, VIDEO_H = 320, 192


def black_frame(w=VIDEO_W, h=VIDEO_H):
    return np.zeros((h, w), np.uint8)


def slide_frame(variant, w=VIDEO_W, h=VIDEO_H):
    """A lit, textured, clearly-not-black frame; `variant` changes the content.

    Successive variants differ over about a third of the frame, comfortably
    above video_metrics.SLIDE_CHANGE_DIFF (2.5 mean absolute levels) -- a real
    slide transition averages far more than that, and the threshold exists to
    sit clear of pointer movement and encoder noise.
    """
    f = np.full((h, w), 40, np.uint8)
    f[20 * h // 192:80 * h // 192, 20:200] = 220
    f[90 * h // 192:170 * h // 192, 20:w - 20] = np.uint8(30 + (variant % 6) * 40)
    return f


def pillarboxed_frame(variant, w=VIDEO_W, h=VIDEO_H):
    """A 4:3 deck inside a 16:9 frame: permanent black bars left and right."""
    f = black_frame(w, h)
    x0, x1 = w // 8, w - w // 8          # centre three quarters
    f[:, x0:x1] = 40
    f[20 * h // 192:80 * h // 192, x0 + 10:x1 - 10] = 220
    f[90 * h // 192:170 * h // 192, x0 + 5:x1 - 5] = \
        np.uint8(30 + (variant % 6) * 40)
    return f


def write_gray_video(path, frames, fps=10, w=VIDEO_W, h=VIDEO_H):
    """Encode grayscale numpy frames to H.264, every frame a keyframe.

    `-g 1` matters: src.scan.media.iter_frames samples the keyframe grid, so
    an all-keyframe file makes the frame sequence the test wrote exactly the
    frame sequence the measurement sees. `-qp 0` keeps luma lossless so the
    black/lit thresholds in video_metrics are not decided by the encoder.
    """
    cmd = ["ffmpeg", "-y", "-v", "error", "-f", "rawvideo", "-pix_fmt", "gray",
           "-s", f"{w}x{h}", "-r", str(fps), "-i", "-",
           "-c:v", "libx264", "-preset", "ultrafast", "-qp", "0",
           "-g", "1", "-pix_fmt", "yuv420p", path]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE,
                            stdout=subprocess.DEVNULL,
                            stderr=subprocess.PIPE)
    try:
        for f in frames:
            proc.stdin.write(np.asarray(f, dtype=np.uint8).tobytes())
        proc.stdin.close()
    except BrokenPipeError:                                     # pragma: no cover
        pass
    err = proc.stderr.read().decode("utf-8", "replace")
    proc.stderr.close()
    if proc.wait() != 0:                                        # pragma: no cover
        raise RuntimeError(f"ffmpeg failed writing {path}: {err}")
    return path


# --------------------------------------------------------------------------
# Metric dictionaries, built from the rubric so they cannot go stale
# --------------------------------------------------------------------------

def good_value(mid):
    """A raw value that scores 1.0 for this metric."""
    scale = rubric.METRICS[mid]["scale"]
    if scale[0] == "bool":
        return True
    if scale[0] == "ramp":
        return scale[2]
    _, _hl, lo, hi, _hh = scale
    return (lo + hi) / 2.0


def mediocre_value(mid, fraction=0.4):
    """A raw value that scores partially, so remediation has something to do."""
    scale = rubric.METRICS[mid]["scale"]
    if scale[0] == "bool":
        return False
    if scale[0] == "ramp":
        _, bad, good = scale
        return bad + fraction * (good - bad)
    _, hard_lo, lo, _hi, _hh = scale
    return hard_lo + fraction * (lo - hard_lo)


def full_metrics(quality="good"):
    """Every rubric metric measured, plus the raw fields the gates read."""
    pick = good_value if quality == "good" else mediocre_value
    m = {mid: pick(mid) for mid in rubric.METRICS}
    m["duration_s"] = 4773.7
    m["duration_min"] = 4773.7 / 60.0
    m["speech_pct"] = 55.0
    m["asr_confidence"] = -0.5
    m["instructor_in_frame_pct"] = 85.0
    return m


PROBE_METRICS = {
    # Exactly what scanner.py's probe tier writes: no audio, no frames, no
    # transcript. Three of these are rubric metrics and all three look fine.
    "duration_s": 4773.7,
    "duration_min": 4773.7 / 60.0,
    "camera_height": 1080,
    "screen_height": 1080,
    "chapter_count": 6,
    "est_pipeline_hours": 2.5,
}


def probe_info(camera=True, audio=True, screen=True,
               cam_duration=4773.7, scr_duration=5000.0):
    """The `probe_info` shape score.evaluate expects."""
    cam = None
    if camera:
        cam = {"path": "camera.mp4", "has_video": True, "has_audio": audio,
               "duration": cam_duration, "width": 1920, "height": 1080}
    scr = None
    if screen:
        scr = {"path": "screen.mp4", "has_video": True, "has_audio": False,
               "duration": scr_duration, "width": 1920, "height": 1080}
    return {"camera": cam, "screen": scr}


# --------------------------------------------------------------------------
# Transcripts
# --------------------------------------------------------------------------

def words(count, start, end, speaker, stem="alpha"):
    """`count` evenly-spaced word entries with per-word speaker labels."""
    step = (end - start) / float(count)
    return [{"word": f"{stem}{i}",
             "start": start + i * step,
             "end": start + (i + 1) * step,
             "speaker": speaker} for i in range(count)]
